# Generated by Django 6.0.5 on 2026-05-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_posiciongps_velocidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posiciongps',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='posiciongps',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='posiciongps',
            name='velocidad',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
